### ISSUE TITLE
deno_std_node_fs.js error

### ISSUE THREAD

**Issue by tvortsa** [codehz/deno-pug#2]
Hi!

few days ago i get this error when i try to reload deno cache:

![image](https://user-images.githubusercontent.com/78345/140815092-dd41ae35-3f3d-4b5c-85b8-c079b83f0d49.png)

here is a map dependences:
![image](https://user-images.githubusercontent.com/78345/140815190-de766a69-7481-45d8-9d46-5bdf5ea2301d.png)

can you help me please?

**Comment by codehz** [comment]
fixed in v0.1.2

**Comment by tvortsa** [comment]
Great, thank you!

ср, 10 нояб. 2021 г., 11:27 Code Hz ***@***.***>:
