### ISSUE TITLE
wrong link : https://esm.sh/v111/pug@3.0.2/deno/pug.bundle.js

### ISSUE THREAD

**Issue by riverfeya** [codehz/deno-pug#5]
I get this error:

error: The deployment failed: HTTP status server error (500 Internal Server Error) for url (https://esm.sh/v111/pug@3.0.2/deno/pug.bundle.js)

Hope it can be fix, thank you!

**Comment by codehz** [comment]
should fix in ffc49b6817fbb694b681e35975afc239bbdfc758
